create table account (id bigint generated by default as identity, primary key (id))
create table account_limit_by_type (account_id bigint not null, limit_by_type_id bigint not null, primary key (account_id, limit_by_type_id))
create table account_limit (id bigint generated by default as identity, balance bigint not null check (balance>=0), type integer, primary key (id))
alter table account_limit_by_type add constraint UK_naciqlrprhy5gqxqrd34t8w3j unique (limit_by_type_id)
alter table account_limit_by_type add constraint FKr32t6ok834a0ceypwmhlhapq8 foreign key (limit_by_type_id) references account_limit
alter table account_limit_by_type add constraint FKsnrg0x53mjffb0us10bpwtpun foreign key (account_id) references account
