create table operation_type (id bigint generated by default as identity, charge_order bigint check (charge_order>=0), description varchar(20), limit_type varchar(255) not null, primary key (id))
create table payment (id bigint not null, amount bigint, credit_id bigint, debit_id bigint, primary key (id))
create table transaction (id bigint generated by default as identity, account_id bigint not null, amount bigint not null, balance bigint not null, due_date bigint not null, event_date bigint not null, operation_type_id bigint not null, primary key (id))
alter table payment add constraint FKi80joa6wad5m5sfelxfwr75pr foreign key (credit_id) references transaction
alter table payment add constraint FK4ndkbeyre4rastc3t9mcwkse9 foreign key (debit_id) references transaction
alter table transaction add constraint FKj2jvxwruf2hchy3jj25ne5m07 foreign key (operation_type_id) references operation_type
